from database import SessionLocal
from models import Question

db = SessionLocal()

questions = [
    # =================== JAVASCRIPT ===================
    Question(question_text="What is JavaScript?", expected_answer="JavaScript is a lightweight interpreted programming language used to make web pages interactive. It runs in the browser and supports object oriented functional and event driven programming styles.", category="JavaScript", difficulty="easy"),
    Question(question_text="What is the difference between var, let and const?", expected_answer="var is function scoped and can be redeclared and updated. let is block scoped and can be updated but not redeclared. const is block scoped and cannot be updated or redeclared. let and const were introduced in ES6.", category="JavaScript", difficulty="easy"),
    Question(question_text="What is a closure in JavaScript?", expected_answer="A closure is a function that has access to variables from its outer scope even after the outer function has returned. Closures remember the environment in which they were created.", category="JavaScript", difficulty="medium"),
    Question(question_text="What is the difference between == and === in JavaScript?", expected_answer="== is loose equality and compares values after type conversion. === is strict equality and compares both value and type without conversion. It is recommended to use === to avoid unexpected type coercion.", category="JavaScript", difficulty="easy"),
    Question(question_text="What is a Promise in JavaScript?", expected_answer="A Promise is an object that represents the eventual completion or failure of an asynchronous operation. It has three states pending fulfilled and rejected. Promises help avoid callback hell and make async code more readable.", category="JavaScript", difficulty="medium"),
    Question(question_text="What is async await in JavaScript?", expected_answer="Async await is syntactic sugar built on top of Promises that makes asynchronous code look and behave like synchronous code. The async keyword declares an asynchronous function and await pauses execution until the Promise resolves.", category="JavaScript", difficulty="medium"),
    Question(question_text="What is the DOM?", expected_answer="The DOM or Document Object Model is a programming interface for web documents. It represents the page as a tree of objects that JavaScript can manipulate to change the structure style and content of a webpage dynamically.", category="JavaScript", difficulty="easy"),
    Question(question_text="What is event bubbling in JavaScript?", expected_answer="Event bubbling is when an event triggered on a child element bubbles up through its parent elements in the DOM tree. The event starts at the target element and propagates upward to the root unless stopped using stopPropagation.", category="JavaScript", difficulty="medium"),
    Question(question_text="What is the difference between null and undefined?", expected_answer="undefined means a variable has been declared but not assigned a value. null is an intentional assignment representing no value or empty value. typeof undefined returns undefined while typeof null returns object.", category="JavaScript", difficulty="easy"),
    Question(question_text="What are arrow functions in JavaScript?", expected_answer="Arrow functions are a shorter syntax for writing functions introduced in ES6. They use the => syntax and do not have their own this binding. They are best used for non method functions and callbacks.", category="JavaScript", difficulty="easy"),

    # =================== PYTHON (expand to 10) ===================
    Question(question_text="What is the difference between deepcopy and shallow copy?", expected_answer="A shallow copy creates a new object but references the same nested objects as the original. A deep copy creates a completely independent copy including all nested objects. Deep copy uses the copy.deepcopy function.", category="Python", difficulty="medium"),
    Question(question_text="What is list comprehension in Python?", expected_answer="List comprehension is a concise way to create lists in Python using a single line of code. It consists of an expression followed by a for clause and optional conditions inside square brackets.", category="Python", difficulty="easy"),
    Question(question_text="What is the difference between is and == in Python?", expected_answer="== checks if two objects have the same value while is checks if two objects are the same object in memory. is compares identity while == compares equality.", category="Python", difficulty="easy"),
    Question(question_text="What are Python lambda functions?", expected_answer="Lambda functions are small anonymous functions defined using the lambda keyword. They can have multiple arguments but only one expression. They are useful for short throwaway functions passed as arguments.", category="Python", difficulty="easy"),
    Question(question_text="What is exception handling in Python?", expected_answer="Exception handling in Python uses try except finally blocks to handle runtime errors gracefully. Code that might raise an error is placed in the try block and the except block handles the error if it occurs.", category="Python", difficulty="medium"),

    # =================== SQL (expand to 10) ===================
    Question(question_text="What is a foreign key?", expected_answer="A foreign key is a column that creates a link between two tables by referencing the primary key of another table. It enforces referential integrity ensuring that relationships between tables remain consistent.", category="SQL", difficulty="easy"),
    Question(question_text="What is the difference between UNION and UNION ALL?", expected_answer="UNION combines results from two queries and removes duplicate rows. UNION ALL combines results and keeps all duplicates. UNION ALL is faster because it does not need to check for duplicates.", category="SQL", difficulty="medium"),
    Question(question_text="What are aggregate functions in SQL?", expected_answer="Aggregate functions perform calculations on a set of values and return a single value. Common aggregate functions include COUNT SUM AVG MIN and MAX. They are often used with GROUP BY clause.", category="SQL", difficulty="easy"),
    Question(question_text="What is a subquery in SQL?", expected_answer="A subquery is a query nested inside another query. It can be used in SELECT FROM and WHERE clauses. Subqueries are used to return data that will be used by the main query as a condition.", category="SQL", difficulty="medium"),
    Question(question_text="What is a stored procedure?", expected_answer="A stored procedure is a prepared SQL code that can be saved and reused. It is stored in the database and can accept parameters return results and perform complex operations. It improves performance and reduces code duplication.", category="SQL", difficulty="medium"),

    # =================== HR (expand to 10) ===================
    Question(question_text="How do you handle conflict with a teammate?", expected_answer="A good answer mentions staying calm listening to the other person finding common ground focusing on the issue not the person and working together to find a solution. Give a real example if possible.", category="HR", difficulty="medium"),
    Question(question_text="Tell me about a time you failed.", expected_answer="A good answer honestly describes a failure takes responsibility for it explains what was learned and shows how it led to improvement. Avoid blaming others and focus on growth.", category="HR", difficulty="medium"),
    Question(question_text="What motivates you?", expected_answer="A good answer mentions intrinsic motivators like learning new skills solving challenging problems making an impact and growing professionally. Align your motivation with the job role.", category="HR", difficulty="easy"),
    Question(question_text="How do you prioritize tasks when you have multiple deadlines?", expected_answer="A good answer mentions techniques like making a priority list breaking tasks into smaller steps focusing on high impact tasks first communicating with stakeholders and using tools like calendars or task managers.", category="HR", difficulty="medium"),
    Question(question_text="Why should we hire you?", expected_answer="A good answer highlights your relevant skills experience and achievements shows enthusiasm for the role explains how you can add value to the company and differentiates you from other candidates.", category="HR", difficulty="easy"),

    # =================== DATA STRUCTURES (expand to 10) ===================
    Question(question_text="What is a graph data structure?", expected_answer="A graph is a non linear data structure consisting of nodes called vertices connected by edges. Graphs can be directed or undirected weighted or unweighted. They are used to represent networks roads social connections and more.", category="Data Structures", difficulty="medium"),
    Question(question_text="What is the difference between BFS and DFS?", expected_answer="BFS or Breadth First Search explores nodes level by level using a queue. DFS or Depth First Search explores as far as possible along each branch using a stack or recursion. BFS finds shortest paths while DFS is good for topological sorting.", category="Data Structures", difficulty="medium"),
    Question(question_text="What is a heap data structure?", expected_answer="A heap is a complete binary tree where each node is greater than or equal to its children in a max heap or less than or equal in a min heap. Heaps are used to implement priority queues and the heap sort algorithm.", category="Data Structures", difficulty="medium"),
    Question(question_text="What is dynamic programming?", expected_answer="Dynamic programming is a method for solving complex problems by breaking them into overlapping subproblems and storing solutions to avoid recomputation. It uses memoization or tabulation and is used in problems like fibonacci knapsack and shortest path.", category="Data Structures", difficulty="hard"),
    Question(question_text="What is the time complexity of binary search?", expected_answer="Binary search has a time complexity of O log n. It works by repeatedly dividing the search interval in half. It requires the array to be sorted and is much faster than linear search which is O n.", category="Data Structures", difficulty="easy"),

    # =================== SYSTEM DESIGN (expand to 10) ===================
    Question(question_text="What is microservices architecture?", expected_answer="Microservices architecture is an approach where an application is built as a collection of small independent services that communicate via APIs. Each service handles a specific business function can be deployed independently and can use different technologies.", category="System Design", difficulty="hard"),
    Question(question_text="What is a CDN?", expected_answer="A CDN or Content Delivery Network is a distributed network of servers that delivers web content to users based on their geographic location. It reduces latency improves load times and decreases the load on the origin server.", category="System Design", difficulty="medium"),
    Question(question_text="What is Docker?", expected_answer="Docker is a platform that uses containerization to package applications and their dependencies into containers. Containers are lightweight portable and consistent across different environments making deployment easier and more reliable.", category="System Design", difficulty="medium"),
    Question(question_text="What is the difference between horizontal and vertical scaling?", expected_answer="Vertical scaling means adding more resources like CPU or RAM to an existing server. Horizontal scaling means adding more servers to distribute the load. Horizontal scaling is more flexible and fault tolerant but more complex to implement.", category="System Design", difficulty="medium"),
    Question(question_text="What is an API gateway?", expected_answer="An API gateway is a server that acts as an entry point for all client requests to backend services. It handles routing authentication rate limiting load balancing and logging. It simplifies client communication in microservices architecture.", category="System Design", difficulty="medium"),
]

db.add_all(questions)
db.commit()
db.close()

print(f"✅ Added {len(questions)} new questions successfully!")